on: 
  push:
    branches:
      -main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.faysalswe.com
        username: faysalsw@portfolios.faysalswe.com
        password: YAT5+4d[1x4Dnb
        server-dir: /portfolios.faysalsw.com/faysalsw
